
const fs = require('fs'); const path = require('path');
const root = path.resolve(__dirname,'..'); const dist = path.join(root,'dist');
const read = f => JSON.parse(fs.readFileSync(path.join(root,'data',f),'utf8'));
const site=read('site.json'), questions=read('questions.json'), lessons=read('lessons.json'), videos=read('videos.json'), routes=read('routes.json');
fs.rmSync(dist,{recursive:true,force:true}); fs.mkdirSync(dist,{recursive:true});
function copyDir(src,dst){ if(!fs.existsSync(src)) return; fs.mkdirSync(dst,{recursive:true}); for(const e of fs.readdirSync(src,{withFileTypes:true})){ const s=path.join(src,e.name), d=path.join(dst,e.name); e.isDirectory()?copyDir(s,d):fs.copyFileSync(s,d);} }
copyDir(path.join(root,'public'),dist);
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function out(url,html){ let p=path.join(dist,url); if(url.endsWith('/')) p=path.join(p,'index.html'); else if(!path.extname(p)) p=path.join(p,'index.html'); fs.mkdirSync(path.dirname(p),{recursive:true}); fs.writeFileSync(p,html); }
function layout({title,description,body,canonical='',schema=''}){ const url=(site.domain||'')+canonical; return `<!doctype html><html lang="ro"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(url)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="/styles.css">${schema?`<script type="application/ld+json">${schema}</script>`:''}</head><body><header class="nav"><div class="nav-inner"><a class="brand" href="/">${esc(site.name)}</a><nav class="nav-links"><a href="/lectii/">Lecții</a><a href="/intrebari/">Întrebări</a><a href="/examen/categoria-b/">Examen</a><a href="/video/">Video</a><a href="/trasee/">Trasee</a></nav></div></header>${body}<footer class="footer">${esc(site.name)} · proiect static SEO pentru învățare Categoria B</footer><script src="/app.js" defer></script></body></html>`;}
function qCard(q){return `<a class="card glass" href="/intrebari/${q.slug}/"><span class="pill">${q.id}</span><h3>${esc(q.title)}</h3><p class="muted">${esc(q.answers[0]||'')}</p></a>`}
function videoMatches(itemTags=[], lessonTags=[]){return videos.filter(v=>v.tags?.filter(t=>lessonTags.includes(t)).length>=2)}
const lessonBySlug=Object.fromEntries(lessons.map(l=>[l.slug,l]));
// Home
out('/', layout({title:`${site.name} — întrebări Categoria B explicate`, description:site.description, canonical:'/', body:`<main class="wrap"><section class="hero"><div><span class="eyebrow">Categoria B · Examen auto · Învățare curată</span><h1>Învață smart, fără haos vizual.</h1><p class="lead">Întrebări cu imagini, răspunsuri ascunse, explicații, lecții, video-uri și simulare de examen într-un design minimalist inspirat de macOS.</p><div class="toolbar"><a class="btn blue" href="/examen/categoria-b/">Începe simularea</a><a class="btn secondary" href="/lectii/">Vezi lecțiile</a></div></div><div class="glass panel"><h2>Primul import</h2><p class="muted">${questions.length} întrebări importate pentru lecția Indicatoare și marcaje. Structura suportă 203+ întrebări, video-uri și trasee.</p><div class="meta"><span class="pill">SEO slugs</span><span class="pill">Static HTML</span><span class="pill">Sitemap</span></div></div></section><section class="grid">${lessons.slice(0,6).map(l=>`<a class="card glass" href="/lectii/${l.slug}/"><h3>${esc(l.title)}</h3><p class="muted">${esc(l.description)}</p><span class="pill">${l.questionIds.length} întrebări</span></a>`).join('')}</section></main>`}));
// Lessons index
out('/lectii/', layout({title:`Lecții Categoria B — ${site.name}`, description:'Toate lecțiile pentru Categoria B, pregătite pentru întrebări, imagini și video-uri.', canonical:'/lectii/', body:`<main class="wrap"><h1>Lecții Categoria B</h1><p class="lead">Navigare simplă pe capitole. Fiecare lecție poate avea întrebări, video-uri confirmate și sugestii automate.</p><div class="grid">${lessons.map(l=>`<a class="card glass" href="/lectii/${l.slug}/"><h3>${esc(l.title)}</h3><p class="muted">${esc(l.description)}</p><span class="pill">${l.questionIds.length} întrebări</span></a>`).join('')}</div></main>`}));
for(const l of lessons){ const lqs=questions.filter(q=>q.lessonSlug===l.slug); const confirmed=videos.filter(v=>l.confirmedVideoIds?.includes(v.id)); const suggested=videoMatches(videos,l.tags||[]); out(`/lectii/${l.slug}/`, layout({title:`${l.title} — întrebări Categoria B`, description:l.description, canonical:`/lectii/${l.slug}/`, body:`<main class="wrap"><div class="split"><aside class="glass panel sticky"><span class="pill">Lecție</span><h1>${esc(l.title)}</h1><p class="muted">${esc(l.description)}</p><details><summary>Video-uri pentru lecție</summary>${confirmed.length?confirmed.map(v=>`<p><a href="/video/${v.slug}/">${esc(v.title)}</a></p>`).join(''):'<p class="muted">Nu există video-uri confirmate încă. Adaugă link-uri în data/videos.json.</p>'}</details><details><summary>Video-uri sugerate</summary>${suggested.length?suggested.map(v=>`<p><a href="/video/${v.slug}/">${esc(v.title)}</a></p>`).join(''):'<p class="muted">Sugestiile apar automat când există video-uri cu taguri comune.</p>'}</details></aside><section><h2>Întrebări din lecție</h2><input class="search" data-filter="questions" placeholder="Caută întrebare..."><div class="lesson-list" data-list="questions">${lqs.map(qCard).join('') || '<div class="notice">Lecție pregătită. Importă întrebări în data/questions.json.</div>'}</div></section></div></main>`}));}
// Questions index
out('/intrebari/', layout({title:`Întrebări Categoria B — ${site.name}`, description:'Lista întrebărilor Categoria B cu pagini SEO individuale.', canonical:'/intrebari/', body:`<main class="wrap"><h1>Întrebări Categoria B</h1><input class="search" data-filter="questions" placeholder="Caută după text, indicator, marcaj..."><div class="grid" data-list="questions">${questions.map(qCard).join('')}</div></main>`}));
for(const q of questions){ const lesson=lessonBySlug[q.lessonSlug]||{}; const schema=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q.title,'acceptedAnswer':{'@type':'Answer','text':q.explanation||q.answers[q.correctAnswers?.[0]]||''}}]}); out(`/intrebari/${q.slug}/`, layout({title:`${q.title} — Categoria B`, description:`Întrebare Categoria B: ${q.title}`, canonical:`/intrebari/${q.slug}/`, schema, body:`<main class="wrap"><div class="split"><aside class="glass panel sticky"><span class="pill">${esc(q.id)}</span><h1>${esc(q.title)}</h1><p class="muted">Lecție: <a href="/lectii/${lesson.slug||''}/">${esc(lesson.title||q.lessonSlug)}</a></p><div class="toolbar"><a class="btn secondary" href="/lectii/${q.lessonSlug}/">Înapoi la lecție</a><a class="btn blue" href="/examen/categoria-b/">Exersează examen</a></div>${q.needsReview?'<p class="notice">Răspunsurile importate sunt marcate pentru verificare înainte de publicare oficială.</p>':''}</aside><section class="glass panel">${q.image?`<img class="question-img" src="${q.image}" alt="Imagine pentru întrebarea: ${esc(q.title)}" loading="eager">`:''}<div class="answers" data-reveal data-correct="${(q.correctAnswers||[]).join(',')}">${q.answers.map((a,i)=>`<div class="answer" data-index="${i}"><strong>${String.fromCharCode(65+i)}.</strong> ${esc(a)}</div>`).join('')}</div><button class="btn" data-reveal-btn>Arată răspunsul</button><details style="margin-top:16px"><summary>Explicație</summary><p>${esc(q.explanation)}</p></details><details style="margin-top:16px"><summary>Video-uri pentru această întrebare</summary><p class="muted">Nu există video-uri asociate încă. Adaugă ID-urile în câmpul videos din data/questions.json.</p></details></section></div></main>`})); }
// Exam
out('/examen/categoria-b/', layout({title:`Simulare examen Categoria B — ${site.name}`, description:'Simulare examen Categoria B: 26 întrebări, 30 minute, maxim 4 greșeli.', canonical:'/examen/categoria-b/', body:`<main class="wrap exam-shell"><section class="glass panel"><span class="pill">Mod examen</span><h1>Simulare examen Categoria B</h1><p class="muted">26 întrebări · 30 minute · 22 răspunsuri corecte necesare · la 5 greșeli testul este picat. În modul examen nu apar video-uri, explicații sau răspunsuri înainte de final.</p><div id="exam-app"></div></section></main><script>window.__QUESTIONS__=${JSON.stringify(questions.map(q=>({id:q.id,title:q.title,image:q.image,answers:q.answers,correctAnswers:q.correctAnswers})))}</script><script src="/exam.js" defer></script>`}));
// Video
out('/video/', layout({title:`Video-uri Categoria B — ${site.name}`, description:'Bibliotecă video cu taguri și sugestii pentru lecții.', canonical:'/video/', body:`<main class="wrap"><h1>Video-uri</h1><p class="lead">Adaugă link-uri în data/videos.json. Sugestiile apar pe lecții după taguri comune.</p>${videos.length?'<div class="grid">'+videos.map(v=>`<a class="card glass" href="/video/${v.slug}/"><h3>${esc(v.title)}</h3><p class="muted">${esc((v.tags||[]).join(', '))}</p></a>`).join('')+'</div>':'<div class="notice">Nu sunt video-uri încă. Structura este pregătită.</div>'}</main>`}));
// Routes
out('/trasee/', layout({title:`Trasee examen auto — ${site.name}`, description:'Trasee filmate cu capturi, semne și explicații punct cu punct.', canonical:'/trasee/', body:`<main class="wrap"><h1>Trasee examen auto</h1><p class="lead">Adaugă trasee filmate, capturi și explicații clare pentru fiecare punct important.</p><div class="grid">${routes.map(r=>`<a class="card glass" href="/trasee/${r.slug}/"><h3>${esc(r.title)}</h3><p class="muted">${esc(r.description)}</p></a>`).join('')}</div></main>`}));
for(const r of routes){ out(`/trasee/${r.slug}/`, layout({title:`${r.title} — traseu examen Categoria B`, description:r.description, canonical:`/trasee/${r.slug}/`, body:`<main class="wrap"><section class="glass panel"><h1>${esc(r.title)}</h1><p class="lead">${esc(r.description)}</p>${r.videoUrl?`<iframe width="100%" height="420" src="${esc(r.videoUrl)}" loading="lazy"></iframe>`:'<div class="notice">Adaugă link video în data/routes.json.</div>'}</section><section style="margin-top:20px" class="lesson-list">${(r.steps||[]).map(s=>`<article class="glass panel route-step">${s.image?`<img class="question-img" src="${s.image}" alt="${esc(s.title)}">`:'<div class="notice">Imagine traseu aici</div>'}<div><h2>${esc(s.title)}</h2><p>${esc(s.description)}</p></div></article>`).join('')}</section></main>`})); }
// app.js
fs.writeFileSync(path.join(dist,'app.js'), `document.addEventListener('click',e=>{if(e.target.matches('[data-reveal-btn]')){const box=e.target.parentElement.querySelector('[data-reveal]');const good=(box.dataset.correct||'').split(',').filter(Boolean).map(Number);box.querySelectorAll('.answer').forEach(a=>{if(good.includes(Number(a.dataset.index)))a.classList.add('correct')});}});document.querySelectorAll('[data-filter]').forEach(input=>input.addEventListener('input',()=>{const list=document.querySelector('[data-list="'+input.dataset.filter+'"]');if(!list)return;[...list.children].forEach(el=>{el.style.display=el.textContent.toLowerCase().includes(input.value.toLowerCase())?'':'none'})}));`);
fs.writeFileSync(path.join(dist,'exam.js'), `(()=>{const all=(window.__QUESTIONS__||[]).filter(q=>q.correctAnswers&&q.correctAnswers.length);let pool=all.sort(()=>Math.random()-.5).slice(0,26),i=0,wrong=0,correct=0,selected=new Set(),sec=1800;const app=document.getElementById('exam-app');function fmt(s){return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}function render(){if(wrong>=5)return finish(false,'Ai ajuns la 5 greșeli.');if(i>=pool.length)return finish(correct>=22,'Test finalizat.');const q=pool[i];app.innerHTML='<div class="toolbar"><span class="pill">Întrebarea '+(i+1)+'/26</span><span class="pill">Corecte '+correct+'</span><span class="pill">Greșeli '+wrong+'</span><span class="pill" id="timer">'+fmt(sec)+'</span></div><div class="progress"><span style="width:'+((i)/26*100)+'%"></span></div><h2>'+q.title+'</h2>'+(q.image?'<img class="question-img" src="'+q.image+'" alt="">':'')+'<div class="answers">'+q.answers.map((a,n)=>'<label class="answer"><input type="checkbox" value="'+n+'"> '+String.fromCharCode(65+n)+'. '+a+'</label>').join('')+'</div><button class="btn blue" id="send">Trimite răspunsul</button>';document.getElementById('send').onclick=()=>{const got=[...app.querySelectorAll('input:checked')].map(x=>Number(x.value)).sort().join(',');const need=[...q.correctAnswers].sort().join(',');got===need?correct++:wrong++;i++;render();};}function finish(pass,msg){app.innerHTML='<h2>'+(pass?'Ai trecut ✅':'Ai picat ❌')+'</h2><p class="lead">'+msg+' Corecte: '+correct+'. Greșeli: '+wrong+'.</p><button class="btn blue" onclick="location.reload()">Reîncearcă</button>'}setInterval(()=>{sec--;const t=document.getElementById('timer');if(t)t.textContent=fmt(Math.max(sec,0));if(sec<=0)finish(correct>=22,'Timpul a expirat.')},1000);render();})();`);
// sitemap
const urls=['/','/lectii/','/intrebari/','/examen/categoria-b/','/video/','/trasee/',...lessons.map(l=>`/lectii/${l.slug}/`),...questions.map(q=>`/intrebari/${q.slug}/`),...routes.map(r=>`/trasee/${r.slug}/`)];
fs.writeFileSync(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${site.domain}${u}</loc></url>`).join('')}</urlset>`);
console.log('Generated',urls.length,'pages in dist/');
